### ISSUE TITLE
Failure while unpacking resources

### ISSUE THREAD

**Issue by Massimo-Petretich** [ChiaraSolito/CellO_UniWork#1]
Hi Chiara,

I found an issue while running scanpy_cello. It seems that the resources are downloaded at the specified location but the unpacking seems to fail (and therefore scanpy_cello exits with an exception, see below).

I paste the whole traceback.

Best,
Massimo

cello.scanpy_cello(
    adata = x,
    clust_key = 'leiden',
    rsrc_loc = misc_vars.cello_resources_loc,
    algo = 'IR',
    out_prefix = misc_vars.model_prefix
)

       Could not find the CellO resources directory called
        'resources' in 'objects/cello_resources_loc'. Will download resources to current 
        directory.
        
Running command: curl http://deweylab.biostat.wisc.edu/cell_type_classification/resources_v2.0.0.tar.gz > objects/cello_resources_loc/resources_v2.0.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5651M  100 5651M    0     0  29.7M      0  0:03:09  0:03:09 --:--:-- 30.8M
tar (child): resources_v2.0.0.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Running command: tar -C objects/cello_resources_loc -zxf resources_v2.0.0.tar.gz
Running command: rm objects/cello_resources_loc/resources_v2.0.0.tar.gz
Checking if any pre-trained model is compatible with this input dataset...
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
/tmp/ipykernel_248664/3716858982.py in <module>
----> 1 cello.scanpy_cello(
      2     adata = x,
      3     clust_key = 'leiden',
      4     rsrc_loc = misc_vars.cello_resources_loc,
      5     algo = 'IR',

/hpc/scratch/hdd1/mp674001/software/conda_envs/python-3.9_r-4.1_b/lib/python3.9/site-packages/cello/scanpy_cello.py in cello(adata, clust_key, rsrc_loc, algo, out_prefix, model_file, log_dir, term_ids, remove_anatomical_subterms)
    127     else:
    128         # Load or train a model
--> 129         mod = ce._retrieve_pretrained_model(adata, algo, rsrc_loc)
    130         if mod is None:
    131             mod = ce.train_model(

/hpc/scratch/hdd1/mp674001/software/conda_envs/python-3.9_r-4.1_b/lib/python3.9/site-packages/cello/cello.py in _retrieve_pretrained_model(ad, algo, rsrc_loc)
    329                 model_fname
    330             )
--> 331             with open(model_f, 'rb') as f:
    332                 mod = dill.load(f)
    333             feats = mod.classifier.features

FileNotFoundError: [Errno 2] No such file or directory: 'objects/cello_resources_loc/resources/trained_models/ir.dill'

**Comment by ChiaraSolito** [comment]
Hi Massimo,
thank you for opening the issue. The error seems to be that scanpy_cello cannot find the model you're trying to access. Since, from what I got from their tutorials (and the message you got), CellO automatically downloads and searches in his resources, but couldn't find ir.dill in what you're giving him as the resources location, the question I have is: what is misc_vars.cello_resources_loc? Is it an object? I don't recognize it

Anyway I used this tool in my bachelor's trainingship, but neither my tutor nor I are fully aware on how to properly use it, I'll link you to their git: https://github.com/deweylab/CellO, their tutorial: https://github.com/deweylab/CellO/tree/master/tutorial and their article: https://www.sciencedirect.com/science/article/pii/S258900422031110X if you have more specific question.
Best regards,
Chiara

**Comment by Massimo-Petretich** [comment]
Hi Chiara,

Thanks a lot for the clarification. I'll take the issue to the developers.
I place some params variable on the object you mentioned,
cello_resources_loc is just a string containing a path, but that's not the
problem, it gets evaluated like a normal string.

Quite impressive that you can work with these tools already at the
bachelor's internship!

Best,
Massimo

**Comment by ChiaraSolito** [comment]
Thanks a lot!
I'll close the issue, since you're goinge to take it to the developers, hope you'll solve it.
Best regards,
Chiara
